/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_main_menu_helpers_PerformanceMetricHelper */

#ifndef _Included_com_example_main_menu_helpers_PerformanceMetricHelper
#define _Included_com_example_main_menu_helpers_PerformanceMetricHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_main_menu_helpers_PerformanceMetricHelper
 * Method:    performanceMetrics
 * Signature: ([DIDZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_example_main_1menu_helpers_PerformanceMetricHelper_performanceMetrics
  (JNIEnv *, jobject, jdoubleArray, jint, jdouble, jboolean);

#ifdef __cplusplus
}
#endif
#endif
