/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_main_menu_helpers_CurveFitJNI */

#ifndef _Included_com_example_main_menu_helpers_CurveFitJNI
#define _Included_com_example_main_menu_helpers_CurveFitJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_main_menu_helpers_CurveFitJNI
 * Method:    vectorProjection
 * Signature: ([[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_example_main_1menu_helpers_CurveFitJNI_vectorProjection
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
