/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CurveFitJNI */

#ifndef _Included_CurveFitJNI
#define _Included_CurveFitJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CurveFitJNI
 * Method:    performanceMetrics
 * Signature: ([DIDZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_CurveFitJNI_performanceMetrics
  (JNIEnv *, jobject, jdoubleArray, jint, jdouble, jboolean);

#ifdef __cplusplus
}
#endif
#endif
