/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_com_example_main_menu_helpers_CurveFitJNI */

#ifndef _Included_main_java_com_example_main_menu_helpers_CurveFitJNI
#define _Included_main_java_com_example_main_menu_helpers_CurveFitJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_com_example_main_menu_helpers_CurveFitJNI
 * Method:    vectorProjection
 * Signature: ([DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_main_java_com_example_main_1menu_helpers_CurveFitJNI_vectorProjection
  (JNIEnv *, jobject, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
